import pathlib

MOVIE_NODES_PATH = pathlib.Path.cwd() / 'Movielens_data' / 'movie_nodes.csv'
USER_NODES_PATH = pathlib.Path.cwd() / 'Movielens_data' / 'user_nodes.csv'
GRAPH_DATA_PATH = pathlib.Path.cwd() / 'Movielens_data' / 'graph.csv'
TETS_PATH = pathlib.Path.cwd() / 'Movielens_data' /'TET.csv'
TETS_0_7_PATH = pathlib.Path.cwd() / 'Movielens_data' /'TET_0_7.csv'
TETS_1_8_PATH = pathlib.Path.cwd() / 'Movielens_data' /'TET_1_8.csv'
TETS_2_9_PATH = pathlib.Path.cwd() / 'Movielens_data' /'TET_2_9.csv'
TETS_3_0_PATH = pathlib.Path.cwd() / 'Movielens_data' /'TET_3_0.csv'
TETS_4_1_PATH = pathlib.Path.cwd() / 'Movielens_data' /'TET_4_1.csv'
TETS_5_2_PATH = pathlib.Path.cwd() / 'Movielens_data' /'TET_5_2.csv'
TETS_6_3_PATH = pathlib.Path.cwd() / 'Movielens_data' /'TET_6_3.csv'
TETS_7_4_PATH = pathlib.Path.cwd() / 'Movielens_data' /'TET_7_4.csv'
TETS_8_5_PATH = pathlib.Path.cwd() / 'Movielens_data' /'TET_8_5.csv'
TETS_9_6_PATH = pathlib.Path.cwd() / 'Movielens_data' /'TET_9_6.csv'
TETSmt_0_7_PATH = pathlib.Path.cwd() / 'Movielens_data' /'TETmt_0_7.p'
TETSmt_1_8_PATH = pathlib.Path.cwd() / 'Movielens_data' /'TETmt_1_8.p'
TETSmt_2_9_PATH = pathlib.Path.cwd() / 'Movielens_data' /'TETmt_2_9.p'
TETSmt_3_0_PATH = pathlib.Path.cwd() / 'Movielens_data' /'TETmt_3_0.p'
TETSmt_4_1_PATH = pathlib.Path.cwd() / 'Movielens_data' /'TETmt_4_1.p'
TETSmt_5_2_PATH = pathlib.Path.cwd() / 'Movielens_data' /'TETmt_5_2.p'
TETSmt_6_3_PATH = pathlib.Path.cwd() / 'Movielens_data' /'TETmt_6_3.p'
TETSmt_7_4_PATH = pathlib.Path.cwd() / 'Movielens_data' /'TETmt_7_4.p'
TETSmt_8_5_PATH = pathlib.Path.cwd() / 'Movielens_data' /'TETmt_8_5.p'
TETSmt_9_6_PATH = pathlib.Path.cwd() / 'Movielens_data' /'TETmt_9_6.p'
Folds_PATH = pathlib.Path.cwd() / 'Movielens_data' /'Folds.json'