import pathlib

MOVIE_NODES_PATH = pathlib.Path.cwd() / 'Movielens_data' / 'movie_nodes.csv'
USER_NODES_PATH = pathlib.Path.cwd() / 'Movielens_data' / 'user_nodes.csv'
GRAPH_DATA_PATH = pathlib.Path.cwd() / 'Movielens_data' / 'graph.csv'
TETS_PATH = pathlib.Path.cwd() / 'Movielens_data' /'TET.csv'
TETS_0_7_PATH = pathlib.Path.cwd() / 'Movielens_data' /'TET_0_7.csv'
TETS_1_8_PATH = pathlib.Path.cwd() / 'Movielens_data' /'TET_1_8.csv'
TETS_2_9_PATH = pathlib.Path.cwd() / 'Movielens_data' /'TET_2_9.csv'
TETS_3_0_PATH = pathlib.Path.cwd() / 'Movielens_data' /'TET_3_0.csv'
TETS_4_1_PATH = pathlib.Path.cwd() / 'Movielens_data' /'TET_4_1.csv'
TETS_5_2_PATH = pathlib.Path.cwd() / 'Movielens_data' /'TET_5_2.csv'
TETS_6_3_PATH = pathlib.Path.cwd() / 'Movielens_data' /'TET_6_3.csv'
TETS_7_4_PATH = pathlib.Path.cwd() / 'Movielens_data' /'TET_7_4.csv'
TETS_8_5_PATH = pathlib.Path.cwd() / 'Movielens_data' /'TET_8_5.csv'
TETS_9_6_PATH = pathlib.Path.cwd() / 'Movielens_data' /'TET_9_6.csv'
Folds_PATH = pathlib.Path.cwd() / 'Movielens_data' /'Folds.json'