name: Build LaTeX document
on:
  #push:
    #branches: 
      #- master
      #- develop
  pull_request:
    branches:
      - master
      - develop
    
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          working_directory: paper
          root_file: main.tex
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: P8Paper
          path: paper
        

